server:
  port: ${sp.sample}
spring:
  application:
    name: ${sn.sample}
seata:
  enabled: true
  tx-service-group: tx-business
  service:
    #seata服务地址
    grouplist:
      default: ${seata.default}
    #虚拟组和分组映射，key的名字与tx-service-group一致
    vgroup-mapping:
      tx-business: default
    #开启全局事务
    disable-global-transaction: false

# 设置日志级别为debug用于测试ELK记录日志
logging:
  level:
    root: debug